"""Golden suite: normalizer behavior pinned vector by vector.

vectors.json is generated by tests/golden/normalizer/generate_vectors.py
from spec-derived tables (it never imports this package). Each vector pins
the full ordered list of case-citation occurrences for one input text on
the five contract fields: as_written, canonical, registry, disposition,
kind. Exact match, no floors: this suite is the contract.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from nvnm_cite.normalizer import normalize

VECTORS_PATH = Path(__file__).parent / "golden" / "normalizer" / "vectors.json"
PAYLOAD = json.loads(VECTORS_PATH.read_text(encoding="utf-8"))
VECTORS = PAYLOAD["vectors"]


def _observed(text: str) -> list[dict]:
    result = normalize(text)
    return [
        {
            "as_written": c.as_written,
            "canonical": c.canonical,
            "registry": c.registry,
            "disposition": c.disposition.value,
            "kind": c.kind,
        }
        for c in result.citations
    ]


@pytest.mark.parametrize("vector", VECTORS, ids=[v["id"] for v in VECTORS])
def test_golden_vector(vector: dict) -> None:
    observed = _observed(vector["text"])
    assert observed == vector["expect"], (
        f"\nvector {vector['id']} ({vector['category']})"
        f"\ntext: {vector['text']!r}"
        f"\nexpected: {json.dumps(vector['expect'], indent=2, ensure_ascii=False)}"
        f"\nobserved: {json.dumps(observed, indent=2, ensure_ascii=False)}"
    )


def test_suite_size_contract() -> None:
    # Task 1.6 calls for 200+ fixtures; regressions in the generator that
    # silently shrink the suite should fail loudly.
    assert len(VECTORS) >= 200
    assert PAYLOAD["_meta"]["vector_count"] == len(VECTORS)
